# Generated by Django 5.2.8 on 2025-12-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="product",
            name="landed_cost",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
